# ==========================================
# APPIUM SERVER & DEVICE CONFIGURATION
# ==========================================
appium.server.url=http://127.0.0.1:4723/wd/hub
device.name=emulator-5554
platform.name=Android
automation.name=UiAutomator2
app.package=com.research_mantra_official
app.activity=.MainActivity
app.path=C:\\Users\\KIng Research\\Desktop\\RESEARCH_MANTRA_AUTOMATION\\researchmantradebugautonew.apk

# ==========================================
# DATA-DRIVEN TESTING CONTROLLER
# ==========================================
active.user.id=1

# ==========================================
# 10 DUMMY USERS DATABASE
# ==========================================
user.1.mobile=7661935544
user.1.name=vamshi krishna
user.1.email=vamshikrishna101@test.com
user.1.city=Delhi

